version: "3.9"

services:
    app:
        build:
            context: .
            target: development
        environment:
            - HOME=/tmp
            - APP_ENV=${APP_ENV:-dev}
        volumes:
            - "./:/srv/app:rw"
        user: "${DEV_UID:-1000}:${DEV_GID:-1000}"
        restart: unless-stopped
        ports:
            - "8081:80"
        networks:
            - default

networks:
    default: ~
