# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $oauthClientId: '%env(string:CLIENT_ID)%'
            string $oauthClientSecret: '%env(string:CLIENT_SECRET)%'
            string $pimUrl: '%env(string:AKENEO_PIM_URL)%'
            string $projectDir: '%kernel.project_dir%'
            string $dockerVersion: '%env(string:DOCKER_VERSION)%'
            string $applicationVersion: '%env(string:APPLICATION_VERSION)%'
            string $openIdAuthentication: '%env(string:OPENID_AUTHENTICATION)%'
            string $subHashKey: '%env(string:SUB_HASH_KEY)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    GuzzleHttp\ClientInterface:
        factory: [ '@App\Client\ClientFactory', 'create' ]

